/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class b_big_myeyetraccker_OpencvClass */

#ifndef _Included_b_big_myeyetraccker_OpencvClass
#define _Included_b_big_myeyetraccker_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     b_big_myeyetraccker_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
void detect(Mat& frame);
JNIEXPORT void JNICALL Java_b_big_myeyetraccker_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
